export const COACH_TIPS: string[] = [
  'Keep your chest up and your breathing steady through every rep.',
  'Focus on clean movement first, then add speed.',
  'Drive through the floor and stay balanced.',
  'Relax your shoulders and keep your neck long.',
  'Strong core, smooth reps, controlled tempo.',
  'Use the rest period to reset your breathing, not your focus.',
  'Quality reps beat rushed reps every time.',
  'Stay tall through the spine and move with purpose.',
  'Exhale during effort and recover on the return.',
  'Small posture corrections make a big performance difference.',
  'Keep your knees tracking over your toes.',
  'Move with intent, not panic.',
  'Your pace should feel challenging, not chaotic.',
  'Brace first, then explode.',
  'Keep your feet rooted and stable.',
  'Fast is fine, controlled is better.',
  'Protect your form when fatigue starts to creep in.',
  'Stay light on your feet and smooth on transitions.',
  'Use your breath to drive rhythm and control.',
  'If your form slips, slow down for two reps and reset.',
  'Eyes forward, ribs down, core engaged.',
  'Power comes from stability first.',
  'You do not need perfect speed — you need repeatable quality.',
  'Treat every rep like it is your first strong rep.',
  'Leave your ego out and your technique in.',
  'Keep your elbows soft and your shoulders active.',
  'Stay present for this interval only.',
  'Use the countdown to prepare, not to drift.',
  'One great set is built from many focused reps.',
  'Reset your stance before the next burst.',
  'Push hard, then recover with intention.',
  'Tension in the core helps everything else move better.',
  'Think tall posture and quick feet.',
  'Keep your hips level and your movement compact.',
  'Explode on the effort, control the return.',
  'Your rest is part of your performance plan.',
  'Breathe low into your ribs and belly.',
  'Stay aggressive with effort and calm with form.',
  'Use your arms efficiently to support rhythm and balance.',
  'Good mechanics now mean better stamina later.',
  'Drive through the full range you can control well.',
  'Keep your jaw relaxed and your focus sharp.',
  'Move smoothly enough that every rep looks the same.',
  'The goal is consistency, not randomness.',
  'Strong finishers start with disciplined pacing.',
  'Let the timer pressure your effort, not your technique.',
  'Keep tension where you need it and relax what you do not.',
  'When in doubt, simplify and sharpen your form.',
  'Stay quick, stable, and efficient.',
  'Push the ground away on every powerful rep.',
  'Use the warmup to prepare the pattern you want under fatigue.',
  'Your best workout is the one you can repeat tomorrow.',
  'Make every transition clean and deliberate.',
  'Keep your ribcage stacked over your hips.',
  'The last ten seconds still count.',
  'Breathe through the nose if you need to settle the pace.',
  'Strong posture creates strong movement.',
  'Keep your landing soft if you are jumping.',
  'Stay springy, not sloppy.',
  'Your recovery speed improves when you stay calm under effort.',
  'Check your grip, then check your posture.',
  'Use the rest block to shake out tension in your hands and shoulders.',
  'Be quick on the feet and patient with the form.',
  'Drive the movement from your hips and core.',
  'Own the pace instead of chasing it.',
  'This interval deserves your full attention.',
  'Stay braced through the hardest part of the rep.',
  'Good workouts are built on repeatable habits.',
  'Keep your tempo honest when the clock gets loud.',
  'Choose precision before speed when fatigue rises.',
  'A calm face helps a calm nervous system.',
  'Use the exhale to stay powerful and composed.',
  'Finish the rep before you think about the next one.',
  'Keep your feet active and your knees soft.',
  'Even during rest, stay mentally in the session.',
  'Recover on purpose: inhale, relax, reset.',
  'Stay tall and proud through the chest.',
  'Use your core like a seatbelt for every rep.',
  'Think snap and control, not rush and collapse.',
  'If you are doing jump rope, stay relaxed through the wrists.',
  'For cardio intervals, find a rhythm you can own.',
  'Keep your stride short and efficient when moving fast.',
  'Shake out tension before the next round begins.',
  'Your next rep only needs your full focus right now.',
  'Work hard, but leave room for clean movement.',
  'Stay centered over your base of support.',
  'A strong midline makes every movement feel lighter.',
  'Do not waste energy fighting the movement — guide it.',
  'Stay intentional through the final seconds.',
  'Clean mechanics protect progress.',
  'A smooth rep under fatigue is a win.',
  'You are training control as much as conditioning.',
  'Keep your pace honest and sustainable.',
  'Let recovery lower your heart rate, not your discipline.',
  'Stay quick, stay tall, stay focused.',
  'Every round is a chance to move better than the last.',
  'Make the basics beautiful under pressure.',
  'Smooth transitions save energy.',
  'Hold your form when the effort spikes.',
  'The workout rewards consistency more than heroics.',
  'Stay patient in the setup and powerful in the execution.',
  'Strong finish — steady breath, sharp form, confident pace.',
]

export function getRandomCoachTip(previousTip?: string): string {
  if (COACH_TIPS.length === 0) {
    return 'Stay focused, breathe steadily, and keep moving with control.'
  }

  if (COACH_TIPS.length === 1) {
    return COACH_TIPS[0]
  }

  let nextTip = previousTip ?? ''

  while (nextTip === previousTip) {
    nextTip = COACH_TIPS[Math.floor(Math.random() * COACH_TIPS.length)]
  }

  return nextTip
}
